/**
 * MealBuilderConfigurationConstants.java 7 mar. 2021
 *
 */
package org.sylrsykssoft.java.springboot.mealbuilder.boot.configuration;

import static org.sylrsykssoft.java.springboot.mealbuilder.api.configuration.drinks.DrinksApiConstants.DRINK_SCHEMA_NAME;
import static org.sylrsykssoft.java.springboot.mealbuilder.api.configuration.meals.MealsApiConstants.MEAL_SCHEMA_NAME;
import static org.sylrsykssoft.java.springboot.mealbuilder.api.configuration.sauces.SaucesApiConstants.SAUCE_SCHEMA_NAME;
import static org.sylrsykssoft.springboot.common.app.boot.configuration.CommonAppBootConstants.COMMON_APP_BOOT_CONFIGURATION_PROPERTIES_DATASOURCE;

import lombok.experimental.UtilityClass;

/**
 * @author juan.gonzalez.fernandez.jgf
 *
 */
@UtilityClass
public class MealBuilderConfigurationConstants {

	// DATASOURCE //
	public static final String MEAL_BUILDER_APP_BOOT_CONFIGURATION_PROPERTIES_DATASOURCE_DRINKS = COMMON_APP_BOOT_CONFIGURATION_PROPERTIES_DATASOURCE
			+ "." + DRINK_SCHEMA_NAME;
	public static final String MEAL_BUILDER_APP_BOOT_CONFIGURATION_PROPERTIES_DATASOURCE_MEALS = COMMON_APP_BOOT_CONFIGURATION_PROPERTIES_DATASOURCE
			+ "." + MEAL_SCHEMA_NAME;
	public static final String MEAL_BUILDER_APP_BOOT_CONFIGURATION_PROPERTIES_DATASOURCE_SAUCES = COMMON_APP_BOOT_CONFIGURATION_PROPERTIES_DATASOURCE
			+ "." + SAUCE_SCHEMA_NAME;

	// JASYPT //
	public static final String COMMON_APP_BOOT_CONFIGURATION_PROPERTIES_JASYPT_UTIL_PASSWORD = "app.jasypt.encryptor.util.password";
	public static final String COMMON_APP_BOOT_CONFIGURATION_PROPERTIES_JASYPT_UTIL_TEXT_BASIC = "app.jasypt.encryptor.util.text.basic";
	public static final String COMMON_APP_BOOT_CONFIGURATION_PROPERTIES_JASYPT_UTIL_TEXT_STRONG = "app.jasypt.encryptor.util.text.strong";

	// MODELMAPPER //
	public static final String MEAL_BUILDER_APP_BOOT_CONFIGURATION_MODEL_MAPPER_PROPERTIES = "app.modelmapper";
	public static final String MEAL_BUILDER_APP_BOOT_CONFIGURATION_MODEL_MAPPER_EMBEDDABLE_PROPERTIES = MEAL_BUILDER_APP_BOOT_CONFIGURATION_MODEL_MAPPER_PROPERTIES + ".embeddable";
	public static final String MEAL_BUILDER_APP_BOOT_CONFIGURATION_MODEL_MAPPER_MEAL_BUILDER_PROPERTIES = MEAL_BUILDER_APP_BOOT_CONFIGURATION_MODEL_MAPPER_PROPERTIES + ".mealbuilder";
	
	public static final String MEAL_BUILDER_APP_BOOT_CONFIGURATION_MODEL_MAPPER_MEAL_BUILDER_DRINKS_PROPERTIES = MEAL_BUILDER_APP_BOOT_CONFIGURATION_MODEL_MAPPER_MEAL_BUILDER_PROPERTIES + ".drinks";
	public static final String MEAL_BUILDER_APP_BOOT_CONFIGURATION_MODEL_MAPPER_MEAL_BUILDER_MEALS_PROPERTIES = MEAL_BUILDER_APP_BOOT_CONFIGURATION_MODEL_MAPPER_MEAL_BUILDER_PROPERTIES + ".meals";
	public static final String MEAL_BUILDER_APP_BOOT_CONFIGURATION_MODEL_MAPPER_MEAL_BUILDER_INGREDIENTES_PROPERTIES = MEAL_BUILDER_APP_BOOT_CONFIGURATION_MODEL_MAPPER_MEAL_BUILDER_PROPERTIES + ".ingredients";
	public static final String MEAL_BUILDER_APP_BOOT_CONFIGURATION_MODEL_MAPPER_MEAL_BUILDER_SAUCES_PROPERTIES = MEAL_BUILDER_APP_BOOT_CONFIGURATION_MODEL_MAPPER_MEAL_BUILDER_PROPERTIES + ".sauces";
	
	public static final String MEAL_BUILDER_APP_BOOT_CONFIGURATION_MODEL_MAPPER_MEAL_BUILDER_DRINKS_LOCALIZED_DATA_PROPERTIES = MEAL_BUILDER_APP_BOOT_CONFIGURATION_MODEL_MAPPER_MEAL_BUILDER_DRINKS_PROPERTIES + ".localized-data";
	public static final String MEAL_BUILDER_APP_BOOT_CONFIGURATION_MODEL_MAPPER_MEAL_BUILDER_MEALS_LOCALIZED_DATA_PROPERTIES = MEAL_BUILDER_APP_BOOT_CONFIGURATION_MODEL_MAPPER_MEAL_BUILDER_MEALS_PROPERTIES + ".localized-data";
	public static final String MEAL_BUILDER_APP_BOOT_CONFIGURATION_MODEL_MAPPER_MEAL_BUILDER_INGREDIENTES_LOCALIZED_DATA_PROPERTIES = MEAL_BUILDER_APP_BOOT_CONFIGURATION_MODEL_MAPPER_MEAL_BUILDER_INGREDIENTES_PROPERTIES + ".localized-data";
	public static final String MEAL_BUILDER_APP_BOOT_CONFIGURATION_MODEL_MAPPER_MEAL_BUILDER_SAUCES_LOCALIZED_DATA_PROPERTIES = MEAL_BUILDER_APP_BOOT_CONFIGURATION_MODEL_MAPPER_MEAL_BUILDER_SAUCES_PROPERTIES + ".localized-data";
	
	public static final String MEAL_BUILDER_APP_BOOT_CONFIGURATION_MODEL_MAPPER_MEAL_BUILDER_DRINKS_MODEL_PROPERTIES = MEAL_BUILDER_APP_BOOT_CONFIGURATION_MODEL_MAPPER_MEAL_BUILDER_DRINKS_PROPERTIES + ".model";
	public static final String MEAL_BUILDER_APP_BOOT_CONFIGURATION_MODEL_MAPPER_MEAL_BUILDER_MEALS_MODEL_PROPERTIES = MEAL_BUILDER_APP_BOOT_CONFIGURATION_MODEL_MAPPER_MEAL_BUILDER_MEALS_PROPERTIES + ".model";
	public static final String MEAL_BUILDER_APP_BOOT_CONFIGURATION_MODEL_MAPPER_MEAL_BUILDER_INGREDIENTES_MODEL_DATA_PROPERTIES = MEAL_BUILDER_APP_BOOT_CONFIGURATION_MODEL_MAPPER_MEAL_BUILDER_INGREDIENTES_PROPERTIES + ".model";
	public static final String MEAL_BUILDER_APP_BOOT_CONFIGURATION_MODEL_MAPPER_MEAL_BUILDER_SAUCES_MODEL_PROPERTIES = MEAL_BUILDER_APP_BOOT_CONFIGURATION_MODEL_MAPPER_MEAL_BUILDER_SAUCES_PROPERTIES + ".model";

}
