# ===============================
# = LOGGER
# ===============================
logging:
  level:
    root: WARN
    org:
      springframework: ERROR
      springframework.web.client: WARN
      springframework.transaction: WARN 
      apache: WARN
      apache.tomcat: ERROR
      apache.catalina: ERROR
      # Activar para ver peticion SOAP HTTP
      apache.http: ERROR
      apache.kafka: WARN
      apache.activemq: WARN
      hibernate: WARN
      # Activar para ver querys JPA
      hibernate.SQL: WARN
      # Activar para ver parametros de querys JPA
      hibernate.type.descriptor.sql.BasicBinder: WARN
    io:
      app: TRACE
    sun: WARN
    net: WARN
    web: DEBUG
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%"

log4j:
  logger:
    org:
      hibernate:
        type: TRACE
        SQL: DEBUG

spring:
  output:
    ansi:
      enabled: ALWAYS

.level: INFO