spring:
  application:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    url: @project.url@
  data:
    rest:
      base-path: /api/v1
  profiles:
    active: @activatedProperties@
  # Show or not log for each sql query
  jpa:
    generate-ddl: true
    show-sql: true
    database: mysql
    hibernate:
      # Hibernate ddl auto (create, create-drop, update): with "create-drop" the database
      # schema will be automatically created afresh for every start of application
      ddl-auto: create-drop
      globally_quoted_identifiers: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        #dialect: org.hibernate.dialect.MariaDBDialect
  h2:
    console:
      enabled: true
  output:
    ansi:
      enabled: ALWAYS

# ===============================
# = SERVER
# ===============================
server:
  port: 8084
  error:
    whitelabel:
      enable: false
    path: /error


# ===============================
# = LOGGER
# ===============================
logging:
  level:
    root: INFO
    org:
      springframework: WARN
      springframework.web.client: WARN
      springframework.cloud: WARN
      springframework.integration: WARN
      springframework.jdbc.core.JdbcTemplate: WARN
      springframework.transaction: WARN  
      apache: WARN
      apache.commons.jexl2: ERROR
      apache.tomcat: ERROR
      apache.catalina: ERROR
      # Activar para ver peticion SOAP HTTP
      apache.http: ERROR
      apache.kafka: WARN
      apache.activemq: WARN
      hibernate: WARN
      # Activar para ver querys JPA
      hibernate.SQL: WARN
      # Activar para ver parametros de querys JPA
      hibernate.type.descriptor.sql.BasicBinder: WARN
    io:
      app: TRACE
    sun: WARN
    net: WARN
    web: DEBUG
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%"


# ===============================
# = SPRING DOC
# ===============================
# https://springdoc.org/#properties
springdoc:
  api-docs:
    path: /springdoc/v3/api-docs
  swagger-ui:
    path: /springdoc/v3/swagger-ui.html
    #configUrl: /springdoc/v3/api-docs/swagger-config
    #oauth2RedirectUrl: /springdoc/v3/swagger-ui/oauth2-redirect.html

# ===============================
# = APPLICATION
# ===============================
app:
  data:
    # ===============================
    # DATA SOURCE
    # ===============================
    datasource:
      meals:
        driver-class-name: org.mariadb.jdbc.Driver
        schema-name: meals
        url: jdbc:mariadb://localhost:3306/meals
        username: root
        password: root
        configuration:
          maximum-pool-size: 30
      drinks:
        driver-class-name: org.mariadb.jdbc.Driver
        schema-name: drinks
        url: jdbc:mariadb://localhost:3306/drinks
        username: root
        password: root
      sauces:
        driver-class-name: org.mariadb.jdbc.Driver
        schema-name: sauces
        url: jdbc:mariadb://localhost:3306/sauces
        username: root
        password: root
  # ===============================
  # = SPRING DOC
  # ===============================
  springdoc:
    configuration:
      open-api:
        title: @project.name@
        description: @project.description@
        version: @project.version@
        license-name: Apache 2.0
        url: @project.url@
        external-doc-description: Meal Builder Wiki Documentation
        external-doc-url: @project.url@/docs
      admin-api:
        group: meal-builder-app-admin
        base-path: /admin/
      public-api:
        group: meal-builder-app-public
        base-path: /public/
        paths:
          - ${app.springdoc.configuration.public-api.base-path}find/drinks
        