# ===============================
# = APPLICATION
# ===============================
app:
  data:
    # ===============================
    # DATA SOURCE
    # ===============================
    datasource:
      meals:
        username: root
        password: ENC(R3JSfRRGuKviWCZKhhAn2w==)
      drinks:
        username: root
        password: ENC(R3JSfRRGuKviWCZKhhAn2w==)
      sauces:
        username: root
        password: ENC(R3JSfRRGuKviWCZKhhAn2w==)
        