# DEVTOOLS
spring:
  devtools:
    livereload:
      # Enable a livereload.com compatible server.
      enabled: true
      port: 35729
    restart:
      # Additional patterns that should be excluded from triggering a full restart.
      #additional-exclude:
      # Additional paths to watch for changes.
      #additional-paths:
      # Enable automatic restart.
      enable: true
      # Patterns that should be excluded from triggering a full restart.
      exclude: META-INF/maven/**,META-INF/resources/**,resources/**,static/**,public/**,templates/**,**/*Test.class,**/*Tests.class,git.properties
      # Amount of time (in milliseconds) to wait between polling for classpath changes.
      poll-interval: 1000
      # Amount of quiet time (in milliseconds) required without any classpath changes before a restart is triggered.
      quiet-period: 400
      # Name of a specific file that when changed will trigger the restart check. If not specified any classpath file change will trigger the restart.
      #trigger-file:
    # REMOTE DEVTOOLS
    remote:
      # Context path used to handle the remote connection.
      context-path: /.~~spring-boot!~
      debug:
        # Enable remote debug support.
        enabled: true
        # Local remote debug server port.
        local-port: 8000
      proxy:
        # The host of the proxy to use to connect to the remote application.
        #host:  
        # The port of the proxy to use to connect to the remote application. 
        #port:
      restart:
        # Enable remote restart.
        enabled: true
      # A shared secret required to establish a connection (required to enable remote support).
      #secret
      # HTTP header used to transfer the shared secret.
      secret-header-name: X-AUTH-TOKEN
