# ===============================
# = JPA / HIBERNATE
# ===============================
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  # Show or not log for each sql query
  jpa:
    generate-ddl: true
    show-sql: true
    database: mysql
    hibernate:
      # Hibernate ddl auto (create, create-drop, update): with "create-drop" the database
      # schema will be automatically created afresh for every start of application
      ddl-auto: create
      globally_quoted_identifiers: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
app:
  data:
    # ===============================
    # = COMMON
    # ===============================
    common:
      platform: mariadb
      driver-class-name: org.mariadb.jdbc.Driver
      host: localhost
      port: 3306
      root:
        username: root
        password: root
    # ===============================
    # DATA SOURCE
    # ===============================
    datasource:
      meals:
        driver-class-name: ${app.data.common.driver-class-name}
        schema-name: meals
        jdbc-url: jdbc:${app.data.common.platform}://${datasource.common.host}:${app.data.common.port}/${app.data.datasource.meals.schema-name}
        url: jdbc:${app.data.common.platform}://${app.data.common.host}:${app.data.common.port}/${spring.datasource.meals.schema-name}
        username: ${app.data.common.root.username}
        password: ${app.data.common.root.password}
        configuration:
          maximum-pool-size: 30
      drinks:
        driver-class-name: ${app.data.common.driver-class-name}
        schema-name: drinks
        jdbc-url: jdbc:${app.data.common.platform}://${app.data.common.host}:${datasource.common.port}/${app.data.datasource.drinks.schema-name}
        url: jdbc:${app.data.common.platform}://${app.data.common.host}:${datasource.common.port}/${app.datasource.drinks.schema-name}
        username: ${app.data.common.root.username}
        password: ${app.data.common.root.password}
      sauces:
        driver-class-name: ${app.data.common.driver-class-name}
        schema-name: sauces
        jdbc-url: jdbc:${app.data.common.platform}://${app.datasource.common.host}:${app.datasource.common.port}/${app.data.datasource.sauces.schema-name}
        url: jdbc:${app.data.common.platform}://${app.datasource.common.host}:${app.datasource.common.port}/${app.datasource.sauces.schema-name}
        username: ${app.data.common.root.username}
        password: ${app.data.common.root.password}
    