# ===============================
# = SPRING
# ===============================
spring:
  application:
    name: @project.name@
  data:
    rest:
      base-path: /api/v1
  profiles:
    active: @activatedProperties@
  # Show or not log for each sql query
  jpa:
    generate-ddl: true
    show-sql: true
    database: mysql
    hibernate:
      # Hibernate ddl auto (create, create-drop, update): with "create-drop" the database
      # schema will be automatically created afresh for every start of application
      ddl-auto: create-drop
      globally_quoted_identifiers: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        #dialect: org.hibernate.dialect.MariaDBDialect
  h2:
    console:
      enabled: true
  output:
    ansi:
      enabled: ALWAYS

# ===============================
# = SERVER
# ===============================
server:
  port: 8084
  servlet:
    context-path: /MBApp
  error:
    whitelabel:
      enable: false
    path: /error

# ===============================
# = LOGGER
# ===============================
logging:
  level:
    root: INFO
    org:
      springframework: WARN
      springframework.web.client: WARN
      springframework.cloud: WARN
      springframework.integration: WARN
      springframework.jdbc.core.JdbcTemplate: WARN
      springframework.transaction: WARN  
      apache: WARN
      apache.commons.jexl2: ERROR
      apache.tomcat: ERROR
      apache.catalina: ERROR
      # Activar para ver peticion SOAP HTTP
      apache.http: ERROR
      apache.kafka: WARN
      apache.activemq: WARN
      hibernate: WARN
      # Activar para ver querys JPA
      hibernate.SQL: WARN
      # Activar para ver parametros de querys JPA
      hibernate.type.descriptor.sql.BasicBinder: WARN
    io:
      app: TRACE
    sun: WARN
    net: WARN
    web: DEBUG
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%"

# ===============================
# = CREDENTIALS
# ===============================
jasypt:
  encryptor:
    password: Key-MBApp-v1

# ===============================
# = SPRING DOC
# ===============================
# https://springdoc.org/#properties
springdoc:
  api-docs:
    path: /springdoc/v3/api-docs
  swagger-ui:
    operationsSorter: method
    path: /springdoc/v3/swagger-ui.html
    #configUrl: /springdoc/v3/api-docs/swagger-config
    #oauth2RedirectUrl: /springdoc/v3/swagger-ui/oauth2-redirect.html

# ===============================
# = COMMON
# ===============================
common:
  app:
    boot:
      configuration:
        # ===============================
        # DATA SOURCE
        # ===============================
        datasource:
          common:
            platform: mariadb
            driver-class-name: org.mariadb.jdbc.Driver
          drinks:
            schema-data-source: drinksSchemaDataSource
            schema-data-source-properties: drinksSchemaDataSourceProperties
            schema-dataSource-custom-properties: drinksSchemaDataSourceCustomProperties
            entity-manager-factory: drinksEntityManagerFactory
            persistence-unit: drinksPersistenceUnit
            entity-transaction-manager: drinksEntityTransactionManager
            packages:
              - org.sylrsykssoft.java.springboot.mealbuilder.api.model.drinks
            mapping-resources:
              - META-INF/drinks/mapping/ingredient.orm.xml
              - META-INF/drinks/mapping/drink.orm.xml
              - META-INF/drinks/mapping/cocktail.orm.xml
              - META-INF/drinks/mapping/cocktail_ingredient.orm.xml
              - META-INF/drinks/mapping/glass_cocktail.orm.xml
          meals:
            schema-data-source: mealsSchemaDataSource
            schema-data-source-properties: mealsSchemaDataSourceProperties
            schema-dataSource-custom-properties: mealsSchemaDataSourceCustomProperties
            entity-manager-factory: mealsEntityManagerFactory
            persistence-unit: mealsPersistenceUnit
            entity-transaction-manager: mealsEntityTransactionManager
            packages:
              - org.sylrsykssoft.java.springboot.mealbuilder.api.model.meals
            mapping-resources:
              - META-INF/meals/mapping/ingredient.orm.xml
              - META-INF/meals/mapping/category.orm.xml
              - META-INF/meals/mapping/starter/food_starter.orm.xml
              - META-INF/meals/mapping/starter/food_starter_ingredient.orm.xml
              - META-INF/meals/mapping/starter/salad.orm.xml
              - META-INF/meals/mapping/starter/salad_ingredient.orm.xml
              - META-INF/meals/mapping/main/burger.orm.xml
              - META-INF/meals/mapping/main/burger_category.orm.xml
              - META-INF/meals/mapping/main/burger_bread.orm.xml
              - META-INF/meals/mapping/main/burger_ingredient.orm.xml
              - META-INF/meals/mapping/main/sandwich.orm.xml
              - META-INF/meals/mapping/main/sandwich_category.orm.xml
              - META-INF/meals/mapping/main/sandwich_bread.orm.xml
              - META-INF/meals/mapping/main/sandwich_ingredient.orm.xml
              - META-INF/meals/mapping/main/kebab.orm.xml
              - META-INF/meals/mapping/main/kebab_category.orm.xml
              - META-INF/meals/mapping/main/kebab_bread.orm.xml
              - META-INF/meals/mapping/main/kebab_ingredient.orm.xml
              - META-INF/meals/mapping/end/dessert.orm.xml
              - META-INF/meals/mapping/end/dessert_ingredient.orm.xml
          sauces:
            schema-data-source: saucesSchemaDataSource
            schema-data-source-properties: saucesSchemaDataSourceProperties
            schema-dataSource-custom-properties: saucesSchemaDataSourceCustomProperties
            entity-manager-factory: saucesEntityManagerFactory
            persistence-unit: saucesPersistenceUnit
            entity-transaction-manager: saucesEntityTransactionManager
            packages:
              - org.sylrsykssoft.java.springboot.mealbuilder.api.model.sauces
            mapping-resources:
              - META-INF/sauces/mapping/ingredient.orm.xml
              - META-INF/sauces/mapping/sauce.orm.xml
              - META-INF/sauces/mapping/sauce_ingredient.orm.xml
        # ===============================
        # = SPRING DOC
        # ===============================
        springdoc:
          open-api:
            title: @project.name@
            description: @project.description@
            version: @project.version@
            license-name: Apache 2.0
            url: @project.url@
            external-doc-description: Meal Builder Wiki Documentation
            external-doc-url: @project.url@/docs
          admin-api:
            group: meal-builder-app-admin
            base-path: ${app.rest.admin.base-path}
            paths:
              - ${app.rest.admin.base-path}**
            packages:
              - org.sylrsykssoft.java.springboot.mealbuilder.rest.controller.drinks.adminapi
              - org.sylrsykssoft.java.springboot.mealbuilder.rest.controller.meals.adminapi
              - org.sylrsykssoft.java.springboot.mealbuilder.rest.controller.sauces.adminapi
          public-api:
            group: meal-builder-app-public
            base-path: ${app.rest.public.base-path}
            paths:
              - ${app.rest.public.base-path}**
            packages:
              - org.sylrsykssoft.java.springboot.mealbuilder.rest.controller.drinks.publicapi
              - org.sylrsykssoft.java.springboot.mealbuilder.rest.controller.meals.publicapi
              - org.sylrsykssoft.java.springboot.mealbuilder.rest.controller.sauces.publicapi
        # ===============================
        # = JASYPT
        # ===============================
        jasypt:
          simple:
            bean-name-properties: mealBuilderJasyptSimplePBEConfigurationProperties
            bean-name: jasyptStringEncryptor
            # http://www.jasypt.org/api/jasypt/1.8/constant-values.html DEFAULT_ALGORITHM
            algorithm: PBEWithMD5AndDES
            password: ${jasypt.encryptor.password}
            # http://www.jasypt.org/api/jasypt/1.8/constant-values.html DEFAULT_KEY_OBTENTION_ITERATIONS
            key-obtention-iterations: 1000
            # http://www.jasypt.org/api/jasypt/1.8/constant-values.html org.jasypt.salt.RandomSaltGenerator
            salt-generator-className: org.jasypt.salt.RandomSaltGenerator
            provider-name: SunJCE
            pool-size: 1
            # http://www.jasypt.org/api/jasypt/1.8/constant-values.html DEFAULT_STRING_OUTPUT_TYPE
            string-output-type: base64
                
# ===============================
# = APPLICATION
# ===============================
app:
  data:
    # ===============================
    # DATA SOURCE
    # ===============================
    datasource:
      meals:
        driver-class-name: ${common.app.boot.configuration.datasource.common.driver-class-name}
        schema-name: meals
        url: jdbc:mariadb://localhost:3306/meals
        configuration:
          maximum-pool-size: 30
      drinks:
        driver-class-name: ${common.app.boot.configuration.datasource.common.driver-class-name}
        schema-name: drinks
        url: jdbc:mariadb://localhost:3306/drinks
      sauces:
        driver-class-name: ${common.app.boot.configuration.datasource.common.driver-class-name}
        schema-name: sauces
        url: jdbc:mariadb://localhost:3306/sauces
  # ===============================
  # = JASYPT
  # ===============================
  jasypt:
    encryptor:
      util:
        password:
          bean-name-properties: mealBuilderJasyptUtilPasswordEncryptorConfigurationProperties
          bean-name: jasyptUtilPasswordEncryptor
          # http://www.jasypt.org/api/jasypt/1.8/constant-values.html DEFAULT_ALGORITHM
          algorithm: PBEWithMD5AndDES
          # http://www.jasypt.org/api/jasypt/1.8/constant-values.html DEFAULT_KEY_OBTENTION_ITERATIONS
          key-obtention-iterations: 1000
          # http://www.jasypt.org/api/jasypt/1.8/constant-values.html org.jasypt.salt.RandomSaltGenerator
          salt-generator-className: org.jasypt.salt.RandomSaltGenerator
          provider-name: SunJCE
          pool-size: 1
          # http://www.jasypt.org/api/jasypt/1.8/constant-values.html DEFAULT_STRING_OUTPUT_TYPE
          string-output-type: base64
        text:
          basic:
            bean-name-properties: mealBuilderJasyptUtilBasicTextEncryptorConfigurationProperties
            bean-name: jasypUtiltBasicTextEncryptor
          strong:
            bean-name-properties: mealBuilderJasyptUtilStrongTextEncryptorConfigurationProperties
            bean-name: jasypUtiltStrongTextEncryptor
  rest:
    public:
      base-path: ${spring.data.rest.base-path}/public/
    admin:
      base-path: ${spring.data.rest.base-path}/admin/
        